// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWf2ejKmH5AXf8UK7lZPzhzYbTLsdr5zI',
    appId: '1:262479051842:web:abb8e2897a9c5af31f81db',
    messagingSenderId: '262479051842',
    projectId: 'uda-phuongppn2',
    authDomain: 'uda-phuongppn2.firebaseapp.com',
    storageBucket: 'uda-phuongppn2.appspot.com',
    measurementId: 'G-T0ZJZXDL5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc5Mo_eYJw9jrFW40CP4WZVNcI9ERlslg',
    appId: '1:262479051842:android:d8a1fbc059f1f09f1f81db',
    messagingSenderId: '262479051842',
    projectId: 'uda-phuongppn2',
    storageBucket: 'uda-phuongppn2.appspot.com',
  );
}
